### ISSUE TITLE
Show number of times student has been helped today in their box

### ISSUE THREAD

**Issue by jkloosterman** [jamesjuett/help_queue#82]
There are some students who put themselves on the queue many times each day. When multiple staff are servicing the queue, they don't know who these students are. Since we are already tracking the number of times students have signed up in a day for the boost, also show the number of signups in the info box for the student.

**Comment by jamesjuett** [comment]
Hi John - this repository is the old office hours queue. The newer one that's currently live at eecsoh.org is: https://github.com/CarsonHoffman/office-hours-queue

**Comment by jkloosterman** [comment]
Thanks for getting me to the right place!
